FROM cgr.dev/chainguard/glibc-dynamic:latest

# Copy native binary into image
COPY build/native/nativeCompile/lurniq-api /app/lurniq-api

# Workdir inside the container
WORKDIR /app

# Expose the app port
EXPOSE 8080

# Run the native binary
ENTRYPOINT ["./lurniq-api"]
