spring:
  application:
    name: lurniq-api
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Disable for performance
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false  # Disable formatting for performance
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # Jackson Configuration for Java 8 Time
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${BASE_URL:http://localhost:8080}/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
  web:
    resources:
      add-mappings: false
  
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}
        debug: false
  
  # Thymeleaf Configuration for Email Templates
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true  # Enable caching for performance
  
server:
  port: 8080
  compression:
    enabled: true
    mime-types: 
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
    min-response-size: 1024
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    accept-count: 100
    max-connections: 8192
    connection-timeout: 20000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# OAuth2 Configuration
oauth2:
  redirect-url: ${BASE_URL:http://localhost:8080}/auth/success
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:4200}

# Email Configuration
email:
  from: ${EMAIL_FROM:noreply@lurniq.com}
  from-name: ${EMAIL_FROM_NAME:Lurniq Team}
  activation:
    subject: "Activate Your Lurniq Account"
    expiration-hours: 24
    base-url: ${BASE_URL:http://localhost:8080}/auth/activate
  password-reset:
    subject: "Reset Your Lurniq Password"
    expiration-hours: 1
    max-requests-per-hour: 3

logging:
    level:
      org.springframework: INFO
      com.lurniq: INFO
    pattern:
      console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(%logger{36}){blue} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# OpenTelemetry Configuration
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,tracing

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: false